name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: |
          Invoke-WebRequest https://download.ngrok.com/windows/stable/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Auth ngrok
        run: ./ngrok/ngrok.exe authtoken 3FVFM2bLfZuzVrdOfREVlIRnSau_4eA7sUamkxxnfHkcSe66y

      - name: Create RDP user
        run: |
          net user kamel123 Myp@ssw0rd123! /add
          net localgroup administrators kamel123 /add

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok and keep alive
        run: |
          $job = Start-Job -ScriptBlock { ./ngrok/ngrok.exe tcp 3389 --log=stdout }
          Start-Sleep -Seconds 10
          $response = Invoke-WebRequest http://127.0.0.1:4040/api/tunnels -UseBasicParsing
          $json = $response.Content | ConvertFrom-Json
          $url = $json.tunnels[0].public_url
          Write-Host "===================================="
          Write-Host "RDP CONNECTION DETAILS:"
          Write-Host "Server: $url"
          Write-Host "Username: kamel123"
          Write-Host "Password: Myp@ssw0rd123!"
          Write-Host "===================================="
          Write-Host "Waiting for 6 hours..."
          Start-Sleep -Seconds 21600
