name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install ngrok via choco
        run: choco install ngrok -y

      - name: Auth ngrok
        run: ngrok.exe authtoken 3FVFM2bLfZuzVrdOfREVlIRnSau_4eA7sUamkxxnfHkcSe66y

      - name: Create RDP user
        run: |
          net user kamel123 Myp@ssw0rd123! /add
          net localgroup administrators kamel123 /add

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok tunnel
        run: |
          Start-Process -NoNewWindow -FilePath ngrok.exe -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 10
          $retry = 0
          do {
            try {
              $response = Invoke-WebRequest http://127.0.0.1:4040/api/tunnels -UseBasicParsing
              $json = $response.Content | ConvertFrom-Json
              $url = $json.tunnels[0].public_url
              $retry = 10
            } catch {
              $retry++
              Start-Sleep -Seconds 5
            }
          } while ($retry -lt 10)
          Write-Host "===================================="
          Write-Host "RDP CONNECTION DETAILS:"
          Write-Host "Server: $url"
          Write-Host "Username: kamel123"
          Write-Host "Password: Myp@ssw0rd123!"
          Write-Host "===================================="
          Start-Sleep -Seconds 21600
